[package]
name = "epic"
version = "0.1.0"
authors = ["George Karalis <15313012+thorbust@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
